name: Build and deploy PR preview

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        run: |
          FULL_LINKS=1 devenv shell build

      - name: Upload static HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-html
          path: dist/

  deploy-pr-preview:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pr-previews
      url: "https://sgc-dashboard-preview-d98d665658f0.s3-eu-central-2.ionoscloud.com/pr/${{github.event.number}}/index.html"
    steps:
      - uses: actions/checkout@v4
      - name: Download static HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: static-html
          path: dist
      - name: Upload website to S3
        uses: ./.github/actions/minio-upload
        with:
          url: "https://s3-eu-central-2.ionoscloud.com"
          accessKey:  ${{ secrets.S3_ACCESS_KEY }}
          secretKey:  ${{ secrets.S3_SECRET_KEY }}
          bucket: sgc-dashboard-preview-d98d665658f0
          source_dir: dist/
          target_dir: /pr/${{ github.event.number }}
